apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "collaboration-server.fullname" . }}
  labels:
    {{- include "collaboration-server.labels" . | nindent 4 }}
    {{- include "collaboration-server.istio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "collaboration-server.selectorLabels" . | nindent 6 }}
      {{- include "collaboration-server.istio.labels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "collaboration-server.selectorLabels" . | nindent 8 }}
        {{- include "collaboration-server.istio.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "common.images.image" .Values }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: transform
              containerPort: {{ .Values.service.transform }}
              protocol: TCP
            - name: apply
              containerPort: {{ .Values.service.apply }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: URL_OF_TRANSFORM_SERVICE
              value: 0.0.0.0:{{ .Values.service.transform }}
            - name: URL_OF_APPLY_SERVICE
              value: 0.0.0.0:{{ .Values.service.apply }}
            - name: URL_OF_UNIVERSER_SERVICE
              value: {{ .Values.config.univerServer }}
            - name: URL_OF_SNAPSHOT_SERVICE
              value: {{ .Values.config.snapshotServer }}
            - name: SAVE_SHEET_SNAPSHOT_INTERVAL
              value: {{ .Values.config.saveSheetSnapshotInterval | quote }}
            - name: SAVE_DOC_SNAPSHOT_INTERVAL
              value: {{ .Values.config.saveDocSnapshotInterval | quote }}
            - name: X_FEATURE_ID
              value: {{ .Values.istio.version | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
