apiVersion: istiomerger.monime.sl/v1alpha1
kind: VirtualServiceMerge
metadata:
  name: {{ include "collaboration-server.fullname" . }}
  labels:
    {{- include "collaboration-server.labels" . | nindent 4 }}
spec:
  target:
    name: collaboration-server ## the virtual service above
  patch:
    http:
      - match:
          - headers:
              x-feature-id:
                exact: {{ .Values.istio.version | quote }}
            port: {{ .Values.service.apply }}
        route:
          - destination:
              host: collaboration-server
              port: 
                number: {{ .Values.service.apply }}
              subset: {{ .Values.istio.version  | quote }}
      - match:
          - headers:
              x-feature-id:
                exact: {{ .Values.istio.version  | quote }}
            port: {{ .Values.service.transform }}
        route:
          - destination:
              host: collaboration-server
              port: 
                number: {{ .Values.service.transform }}
              subset: {{ .Values.istio.version  | quote }}