apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "universer.fullname" . }}
  labels:
    {{- include "universer.labels" . | nindent 4 }}
    {{- include "universer.istio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "universer.selectorLabels" . | nindent 6 }}
      {{- include "universer.istio.labels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "universer.selectorLabels" . | nindent 8 }}
        {{- include "universer.istio.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "common.images.image" .Values }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.http }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.service.grpc }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: conf
              mountPath: /data/configs/config.yaml
              subPath: config.yaml
            - name: secret
              mountPath: /data/configs/LICENSE
              subPath: LICENSE
            - name: secret
              mountPath: /data/configs/public_key.crt
              subPath: public_key.crt
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: conf
          configMap: 
            name: universer-config
        - name: secret
          secret:
            secretName: universer-secret
