apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "universer.fullname" . }}
  labels:
    {{- include "universer.labels" . | nindent 4 }}
spec:
  host: universer
  subsets:
  - name: {{ .Values.istio.version  | quote }}
    labels:
      version: {{ .Values.istio.version  | quote }}