apiVersion: istiomerger.monime.sl/v1alpha1
kind: VirtualServiceMerge
metadata:
  name: {{ include "universer.fullname" . }}-api
  labels:
    {{- include "universer.labels" . | nindent 4 }}
spec:
  target:
    name: universer-api ## the virtual service above
  patch:
    http:
      - match:
          - headers:
              x-feature-id:
                exact: {{ .Values.istio.version  | quote }}
            {{- if .Values.istio.featureGateway.enabled }}
            authority:
              exact: {{ .Values.istio.featureGateway.host }}
            {{- end }}
        route:
          - destination:
              host: universer
              port: 
                number: {{ .Values.service.http }}
              subset: {{ .Values.istio.version  | quote }}
---
apiVersion: istiomerger.monime.sl/v1alpha1
kind: VirtualServiceMerge
metadata:
  name: {{ include "universer.fullname" . }}-internal
  labels:
    {{- include "universer.labels" . | nindent 4 }}
spec:
  target:
    name: universer-internal ## the virtual service above
  patch:
    http:
      - match:
          - headers:
              x-feature-id:
                exact: {{ .Values.istio.version | quote }}
            port: {{ .Values.service.grpc }}
        route:
          - destination:
              host: universer
              port: 
                number: {{ .Values.service.grpc }}
              subset: {{ .Values.istio.version  | quote }}
