{{- if .Values.istio.enabled -}}
{{- if and (not .Values.ingress.enabled) .Values.istio.gateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "docs.fullname" . }}-gws
  labels:
    {{- include "docs.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ .Values.istio.gateway.host | quote }}
  gateways:
  - work
  http:
  - delegate:
      name: {{ include "docs.fullname" . }}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "docs.fullname" . }}
  labels:
    {{- include "docs.labels" . | nindent 4 }}
spec:
  {{- if not .Values.istio.gateway.enabled }}
  hosts:
    - {{ include "docs.fullname" . | quote }}
  {{- end }}
  http:
    - route:
        - destination:
            host: {{ include "docs.fullname" . }}
            port: 
              number: {{ .Values.service.port }}
            subset: default
{{- end -}}