services:
  universer:
    restart: always
    image: univer-acr-registry.cn-shenzhen.cr.aliyuncs.com/${EDITION}/universer:${UNIVERSER_VERSION}
    expose:
      - 8000
      - 9000
    environment:
      - NO_PROXY=127.0.0.1,localhost,${DOCKER_NETWORK_SUBNET},univer-temporal,collaboration-server,univer-minio
      - SERVICE_NAME=Universer
      - SERVICE_VERSION=${UNIVERSER_VERSION}
    volumes:
      - ./configs:/data/configs
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/univers:/tmp/univers
    depends_on:
      univer-mysql:
        condition: service_started
      univer-rabbitmq:
        condition: service_started
      univer-temporal:
        condition: service_started
      univer-redis:
        condition: service_started
      init-db:
        condition: service_completed_successfully
    networks:
      - univer
    labels:
      - com.univer.app=universer
    deploy:
      replicas: 2
      endpoint_mode: dnsrr

  init-db:
    container_name: init-db
    image: univer-acr-registry.cn-shenzhen.cr.aliyuncs.com/release/universer-sql:${UNIVERSER_SQL_VERSION}-mysql
    environment:
      - HOST=${DATABASE_HOST}
      - PORT=${DATABASE_PORT}
      - USERNAME=${DATABASE_USERNAME}
      - PASSWORD=${DATABASE_PASSWORD}
      - DATABASE=${DATABASE_DBNAME}
      - NO_PROXY=127.0.0.1,localhost,${DOCKER_NETWORK_SUBNET},${DATABASE_HOST}
    networks:
      - univer
    depends_on:
      univer-mysql:
        condition: service_started
    labels:
      - com.univer.app=init-db

  lb:
    restart: always
    image: nginx:alpine-slim
    ports:
     - ${HOST_NGINX_PORT}:8000
    networks:
      - univer
    depends_on:
      - universer
    volumes:
      - ./nginx:/etc/nginx/conf.d/

  collaboration-server:
    restart: always
    container_name: collaboration-server
    image: univer-acr-registry.cn-shenzhen.cr.aliyuncs.com/release/univer-collaboration:${COLLABORATION_SERVER_VERSION}
    environment:
      - URL_OF_APPLY_SERVICE=0.0.0.0:5002
      - URL_OF_UNIVERSER_SERVICE=universer:8000
      - URL_OF_SNAPSHOT_SERVICE=universer:9000
      - SAVE_SHEET_SNAPSHOT_INTERVAL=50
      - SAVE_DOC_SNAPSHOT_INTERVAL=50
      - ENABLE_MUTATION_APPLY_INTERCEPTOR=true
      - no_proxy=127.0.0.1,localhost,${DOCKER_NETWORK_SUBNET},universer
    expose:
      - 5002
    networks:
      - univer
    labels:
      - com.univer.app=collaboration-server

  univer-mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    container_name: univer-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - univer
    labels:
      - com.univer.app=mysql

  univer-rabbitmq:
    restart: always
    container_name: univer-rabbitmq
    image: rabbitmq:${RABBITMQ_VERSION}
    expose:
      - 5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - univer
    labels:
      - com.univer.app=rabbitmq

  univer-redis:
    restart: always
    image: bitnami/redis:${REDIS_VERSION}
    container_name: univer-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
    networks:
      - univer
    labels:
      - com.univer.app=redis
    volumes:
      - redis-data:/bitnami/redis/data

  univer-temporal:
    restart: always
    container_name: univer-temporal
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    environment:
      - DB=mysql
      - MYSQL_SEEDS=${DATABASE_HOST}
      - DB_PORT=${DATABASE_PORT}
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PWD=${DATABASE_PASSWORD}
      - TEMPORAL_CLI_SHOW_STACKS=1
      - NO_PROXY=127.0.0.1,localhost,${DOCKER_NETWORK_SUBNET}
    volumes:
      - ./temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
    expose:
      - 7233
    depends_on:
      - univer-mysql
    networks:
      - univer
    labels:
      - com.univer.app=temporal
  
  univer-minio:
    restart: always
    image: bitnami/minio:${MINIO_VERSION}
    user: root
    container_name: univer-minio
    environment:
      - MINIO_ROOT_USER=${S3_USER}
      - MINIO_ROOT_PASSWORD=${S3_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${S3_DEFAULT_BUCKET}
      - MINIO_DATA_DIR=/data
    ports:
      - ${HOST_MINIO_PORT}:9000
    expose:
      - 9000
    networks:
      - univer
    labels:
      - com.univer.app=minio
    volumes:
      - minio-data:/data

  univer-worker-exchange:
    restart: always
    container_name: univer-worker-exchange
    image: univer-acr-registry.cn-shenzhen.cr.aliyuncs.com/release/worker-exchange:${UNIVER_WORKER_EXCHANGE_VERSION}
    environment:
      - NO_PROXY=127.0.0.1,localhost,${DOCKER_NETWORK_SUBNET},univer-temporal,univer-minio,universer
      - TEMPORAL_SERVER=${TEMPORAL_HOST}:${TEMPORAL_PORT}
      - TEMPORAL_NAMESPACE=${TEMPORAL_NAMESPACE}
      - SERVICE_NAME=exchange-worker
      - SERVICE_VERSION=${UNIVER_WORKER_EXCHANGE_VERSION}
    depends_on:
      - univer-temporal
    networks:
      - univer
    labels:
      - com.univer.app=worker-exchange

  univer-demo-ui:
    image: univer-acr-registry.cn-shenzhen.cr.aliyuncs.com/release/univer-collaboration-lite:${UNIVER_DEMO_UI_VERSION}
    container_name: univer-collaboration-demo-ui
    ports:
      - "3010:3010"
    volumes:
      - ./configs:/data/configs
    networks:
      - univer
    restart: "no"
    profiles:
      - demo-ui

networks:
  univer:
    name: univer-prod
    driver: bridge
    ipam:
     config:
       - subnet: ${DOCKER_NETWORK_SUBNET}

volumes:
  mysql-data:
    name: univer-prod-mysql-data
  redis-data:
    name: univer-prod-redis-data
  minio-data:
    name: univer-prod-minio-data

