apiVersion: v1
kind: Service
metadata:
  name: {{ include "collaboration-server.fullname" . }}
  labels:
    {{- include "collaboration-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.transform }}
      targetPort: transform
      protocol: TCP
      name: grpc-transform
    - port: {{ .Values.service.apply }}
      targetPort: apply
      protocol: TCP
      name: grpc-apply
    - port: {{ .Values.service.nodeSnapshot }}
      targetPort: nodeSnapshot
      protocol: TCP
      name: grpc-node-snapshot
  selector:
    {{- include "collaboration-server.selectorLabels" . | nindent 4 }}
