host: http://localhost:8080

database:
  driver: sqlite
  dsn: demo.db

redis:
  addr: univer-redis:6379

universer:
  host: http://lb:8000

univer:
  docHost: ":3010/pro-demo/docs"
  sheetHost: ":3010/pro-demo/sheet"

font: web/public/font/SourceHanSansCN-VF.ttf