host: http://localhost:8080

server:
  port: 8080

database:
  driver: sqlite
  dsn: demo.db

redis:
  enabled: true
  addr: univer-redis:6379

universer:
  host: http://lb:8000

univer:
  sheetHost: "/sheet"

font: web/public/font/SourceHanSansCN-VF.ttf