{{- if .Values.istio.enabled -}}
{{- if and (not .Values.ingress.enabled) .Values.istio.gateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "universer.fullname" . }}-gws
  labels:
    {{- include "universer.labels" . | nindent 4 }}
spec:
  hosts:
  {{- range .Values.istio.gateway.hosts }}
  - {{ . | quote }}
  {{- end }}
  gateways:
  {{- range .Values.istio.gateway.gateways }}
  - {{ . | quote }}
  {{- end }}
  http:
  {{- range .Values.istio.forbbidenApi }}
  - match:
      - uri:
          regex: {{ . | quote }}
    directResponse:
      status: 403
      body:
        string: "Forbbiden"
  {{- end }}
  - match:
      - uri:
          prefix: "/universer-api/"
    delegate:
      name: {{ include "universer.fullname" . }}-api
    headers:
      request:
        remove: [ x-feature-id ]
{{ end }}
{{- if and (not .Values.ingress.enabled) .Values.istio.featureGateway.enabled -}}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "universer.fullname" . }}-feat-gws
  labels:
    {{- include "universer.labels" . | nindent 4 }}
spec:
  hosts:
  {{- range .Values.istio.featureGateway.hosts }}
  - {{ . | quote }}
  {{- end }}
  gateways:
  {{- range .Values.istio.featureGateway.gateways }}
  - {{ . | quote }}
  {{- end }}
  http:
  {{- range .Values.istio.forbbidenApi }}
  - match:
      - uri:
          regex: {{ . | quote }}
    directResponse:
      status: 403
      body:
        string: "Forbbiden"
  {{- end }}
  - match:
      - uri:
          prefix: "/universer-api/"
    delegate:
      name: {{ include "universer.fullname" . }}-api
{{- end }}
{{- if and (not .Values.ingress.enabled) (or .Values.istio.gateway.enabled .Values.istio.featureGateway.enabled) }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "universer.fullname" . }}-api
  labels:
    {{- include "universer.labels" . | nindent 4 }}
spec:
  http:
    - route:
        - destination:
            host: {{ include "universer.fullname" . }}
            port: 
              number: {{ .Values.service.http }}
            subset: default
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "universer.fullname" . }}-internal
  labels:
    {{- include "universer.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ include "universer.fullname" . | quote }}
  http:
    - match:
        - port: {{ .Values.service.grpc }}
      route:
        - destination:
            host: {{ include "universer.fullname" . }}
            port: 
              number: {{ .Values.service.grpc }}
            subset: default
{{- else -}}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "universer.fullname" . }}
  labels:
    {{- include "universer.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ include "universer.fullname" . | quote }}
  http:
    - match:
        - port: {{ .Values.service.grpc }}
      route:
        - destination:
            host: {{ include "universer.fullname" . }}
            port: 
              number: {{ .Values.service.grpc }}
            subset: default
    - route:
        - destination:
            host: {{ include "universer.fullname" . }}
            port: 
              number: {{ .Values.service.http }}
            subset: default
{{- end }}
{{- end -}}