apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "universer.fullname" . }}-job-config
  labels:
    {{- include "universer.labels" . | nindent 4 }}
data: {{- include "common.tplvalues.render" (dict "value" .Values.job.scripts "context" .) | nindent 2 }}