{{- if .Values.istio.enabled -}}
{{- if and (not .Values.ingress.enabled) .Values.istio.gateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "pro-docs.fullname" . }}
  labels:
    {{- include "pro-docs.labels" . | nindent 4 }}
spec:
  # The selector matches the ingress gateway pod labels.
  # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
  selector:
    {{- with .Values.istio.gateway.ingressSelector -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.istio.gateway.host | quote }}
    {{- if .Values.istio.gateway.tls.enabled }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ .Values.istio.gateway.host | quote }}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.istio.gateway.tls.credentialName | quote }}
    {{- end -}}
{{- end -}}
{{- end -}}