apiVersion: v1
kind: Service
metadata:
  name: {{ template "swagger-ui.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ template "swagger-ui.fullname" . }}