server:
  http:
    addr: 0.0.0.0:{{ .Values.service.http }}
    timeout: 10s
  grpc:
    addr: 0.0.0.0:{{ .Values.service.grpc }}
    timeout: 10s
data:
  database:
    maxOpenConns: {{ .Values.config.postgresql.maxOpenConns }}
    maxIdleConns: {{ .Values.config.postgresql.maxIdleConns }}
    connMaxLifetime: {{ .Values.config.postgresql.connMaxLifetime }}
    driver: postgresql
    database: {{ .Values.config.postgresql.database }}
    dsn: host={{ tpl .Values.config.postgresql.host . }} port={{ .Values.config.postgresql.port }} dbname={{ .Values.config.postgresql.database }} user={{ .Values.config.postgresql.username }} password={{ .Values.config.postgresql.password }} sslmode=disable TimeZone=Asia/Shanghai
  rabbitmq:
    addr: amqp://{{ .Values.config.rabbitmq.username }}:{{ .Values.config.rabbitmq.password }}@{{ tpl .Values.config.rabbitmq.host . }}:{{ .Values.config.rabbitmq.port }}/
  clickhouse:
    dsn: clickhouse://clickhouse:clickhouse@clickhouse:9000/univer?dial_timeout=10s&read_timeout=20s
  temporal:
    addr: {{ tpl .Values.config.temporal.addr . }}
    namespace: {{ .Values.config.temporal.namespace }}
  redis:
    addr: {{ tpl .Values.config.redis.addr . }}
    read_timeout: 0.2s
    write_timeout: 0.2s
  s3:
    accessKeyID: {{ .Values.config.s3.accessKeyID }}
    accessKeySecret: {{ .Values.config.s3.accessKeySecret }}
    region: {{ .Values.config.s3.region }}
    endpoint: {{ .Values.config.s3.endpoint }}
    endpointPublic: {{ .Values.config.s3.endpointPublic }}
    usePathStyle: {{ .Values.config.s3.usePathStyle }}
    presignExpires: {{ .Values.config.s3.presignExpires }}
service:
  transform:
    addr: "{{ tpl .Values.config.transform.host . }}:{{ .Values.config.transform.port }}"
    timeout: 10s
  apply:
    addr: "{{ tpl .Values.config.apply.host . }}:{{ .Values.config.apply.port }}"
    timeout: 10s
  node_snapshot:
    addr: "{{ tpl .Values.config.node_snapshot.host . }}:{{ .Values.config.node_snapshot.port }}"
    timeout: 10s
admin: 
{{- if .Values.config.admin -}}
  {{- range .Values.config.admin }}
  - user: {{ .user }}
    password: {{ .password }}
  {{- end }}
{{- else }} []
{{- end }}
extra:
  celldataMaxSize: 10485760 # 单位字节，10M
auth:
  enabled: {{ .Values.config.auth.enabled }}
  {{- with .Values.config.auth.oidc }}
  oidc:
    {{- toYaml . | nindent 4 }}
  {{- end }}