server:
  http:
    addr: 0.0.0.0:{{ .Values.service.http }}
    timeout: 60s # max timeout, not real timeout
    corsAllowOrigins:
    {{- range .Values.config.server.http.corsAllowOrigins }}
    - {{ . | quote}}
    {{- end }}
  grpc:
    addr: 0.0.0.0:{{ .Values.service.grpc }}
    timeout: 60s # max timeout, not real timeout
  shutdownTimeout: {{ .Values.config.server.shutdownTimeout }}
data:
  database:
    maxOpenConns: {{ .Values.config.database.maxOpenConns }}
    maxIdleConns: {{ .Values.config.database.maxIdleConns }}
    connMaxLifetime: {{ .Values.config.database.connMaxLifetime }}
    driver: {{ .Values.config.database.driver }}
    database: {{ .Values.config.database.dbname }}
    dsn: {{ include "universer.database.dsn" .Values.config.database }}
    replicaDSN: {{ include "universer.database.replicaDSN" .Values.config.database }}
  rabbitmq:
    enabled: {{ .Values.config.rabbitmq.enabled }}
    addr: amqp://{{ .Values.config.rabbitmq.username }}:{{ .Values.config.rabbitmq.password }}@{{ tpl .Values.config.rabbitmq.host . }}:{{ .Values.config.rabbitmq.port }}/
    {{- with .Values.config.rabbitmq.cluster }}
    cluster:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    eventSync: {{ .Values.config.rabbitmq.eventSync }}
  clickhouse:
    dsn: clickhouse://clickhouse:clickhouse@clickhouse:9000/univer?dial_timeout=10s&read_timeout=20s
  temporal:
    addr: {{ tpl .Values.config.temporal.addr . }}
    namespace: {{ .Values.config.temporal.namespace }}
  {{- with .Values.config.redis }}
  redis:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.config.s3 }}
  s3:
    {{- toYaml . | nindent 4 }}
  {{- end }}
service:
  apply:
    addr: "{{ tpl .Values.config.apply.host . }}:{{ .Values.config.apply.port }}"
    timeout: 10s
  nodeRuntime:
    addr: {{ .Values.config.nodeRuntime.addr }}
    timeout: 10s
  pythonRuntime:
    addr: {{ .Values.config.pythonRuntime.addr }}
    timeout: 10s
  yuumi:
    addr: {{ .Values.config.yuumi.addr }}
  {{- if .Values.config.fileExchange.enabled }}
  fileExchange:
    addr: {{ .Values.config.fileExchange.addr }}
  {{- end }}
  ssc:
    addr: "{{ tpl .Values.config.ssc.host . }}:{{ .Values.config.ssc.port }}"
    timeout: 10s
apiLimit:
  {{- with .Values.config.apiLimit }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
admin: 
{{- if .Values.config.admin -}}
  {{- range .Values.config.admin }}
  - user: {{ .user }}
    password: {{ .password }}
  {{- end }}
{{- else }} []
{{- end }}
extra:
  celldataMaxSize: 10485760 # 单位字节，10M
auth:
  enabled: {{ .Values.config.auth.enabled }}
  univerEnabled: {{ .Values.config.auth.univerEnabled }}
  cookieDomain: {{ .Values.config.auth.cookieDomain }}
  loginErrorURL: {{ .Values.config.auth.loginErrorURL }}
  loginURL: {{ .Values.config.auth.loginURL }}
  ssoAuthOrigin: {{ .Values.config.auth.ssoAuthOrigin }}
  mobileBindURL: {{ .Values.config.auth.mobileBindURL }}
  homepageURL: {{ .Values.config.auth.homepageURL }}
  {{- with .Values.config.auth.casdoorSDK }}
  casdoorSDK:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.config.auth.oidc }}
  oidc:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.config.auth.oauth2 }}
  oauth2:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.config.auth.anonymous }}
  anonymous:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.config.auth.permission }}
  permission:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  admin:
    userIDs:
    {{- range .Values.config.auth.admin.userIDs }}
    - {{ . | quote }}
    {{- end }}
    liteServer: {{ .Values.config.auth.admin.liteServer }}
usip:
  enabled: {{ .Values.config.usip.enabled }}
  {{- with .Values.config.usip.uri }}
  uri:
    {{- toYaml . | nindent 4 }}
  {{- end }}
sentryConfig:
  {{- with .Values.config.sentryConfig.dsn }}
  dsn: {{ . }}
  {{- else }}
  dsn: ""
  {{- end }}
  debug: false
  enableTracing: true
  TracesSampleRate: 1.0
dataProtectionConf:
  enableProtection: {{ .Values.config.dataProtectionConf.enableProtection }}
  dataKeyRotate: {{ .Values.config.dataProtectionConf.dataKeyRotate }}
  dataKeyCacheExpiration: {{ .Values.config.dataProtectionConf.dataKeyCacheExpiration }}
  {{- if eq .Values.config.dataProtectionConf.kmsServiceName "aws" }}
  awskms:
    accessKeyID: {{ .Values.config.dataProtectionConf.awskms.accessKeyID }}
    accessKeySecret: {{ .Values.config.dataProtectionConf.awskms.accessKeySecret }}
    region: {{ .Values.config.dataProtectionConf.awskms.region }}
    kmsKeyID: {{ .Values.config.dataProtectionConf.awskms.kmsKeyID }}
  {{- else if eq .Values.config.dataProtectionConf.kmsServiceName "local" }}
  localKMS:
    cmkAlias: {{ .Values.config.dataProtectionConf.localKMS.cmkAlias }}
    cmkBase64: {{ .Values.config.dataProtectionConf.localKMS.cmkBase64 }}
  {{- end }}
sesConfig:
{{- with .Values.config.sesConfig }}
  {{- toYaml . | nindent 2 }}
{{- end }}
smsConf:
{{- with .Values.config.smsConf }}
  {{- toYaml . | nindent 2 }}
{{- end }}
postHogConf:
  enabled: {{ .Values.config.postHogConf.enabled}}
  endpoint: {{ default "" .Values.config.postHogConf.endpoint}}
  projectKey: {{ default "" .Values.config.postHogConf.projectKey}}
entitlementConf:
  enable: {{ .Values.config.entitlementConf.enable }}
  defaultEntiConf:
    anonymousDefaultEntiId: {{ .Values.config.entitlementConf.defaultEntiConf.anonymousDefaultEntiId }}
    registeredDefaultEntiId: {{ .Values.config.entitlementConf.defaultEntiConf.registeredDefaultEntiId }}
  cronConf:
    reportRetryCron: {{ .Values.config.entitlementConf.cronConf.reportRetryCron | quote }}
    minRetryInterval: {{ .Values.config.entitlementConf.cronConf.minRetryInterval }}
    retryRate: {{ .Values.config.entitlementConf.cronConf.retryRate }}
    pendingSubCleanCron: {{ .Values.config.entitlementConf.cronConf.pendingSubCleanCron | quote }}
    detectInterval: {{ .Values.config.entitlementConf.cronConf.detectInterval }}
    cleanRate: {{ .Values.config.entitlementConf.cronConf.cleanRate }}
  stripeConf:
    apiPK: {{ .Values.config.entitlementConf.stripeConf.apiPK | quote }}
    apiSK: {{ .Values.config.entitlementConf.stripeConf.apiSK | quote }}
    whSK: {{ .Values.config.entitlementConf.stripeConf.whSK | quote }}
    timeout: {{ .Values.config.entitlementConf.stripeConf.timeout }}
  wechatPayConf:
    appID: {{ .Values.config.entitlementConf.wechatPayConf.appID | quote }}
    mchCertificateSerialNumber: {{ .Values.config.entitlementConf.wechatPayConf.mchCertificateSerialNumber | quote }}
    mchID: {{ .Values.config.entitlementConf.wechatPayConf.mchID | quote }}
    apiKey: {{ .Values.config.entitlementConf.wechatPayConf.apiKey | quote }}
    notifyUrl: {{ .Values.config.entitlementConf.wechatPayConf.notifyUrl | quote }}
  aliPayConf:
    appID: {{ .Values.config.entitlementConf.aliPayConf.appID | quote }}
    privateKey: {{ .Values.config.entitlementConf.aliPayConf.privateKey | quote }}
    apiKey: {{ .Values.config.entitlementConf.aliPayConf.apiKey | quote }}
    notifyUrl: {{ .Values.config.entitlementConf.aliPayConf.notifyUrl | quote }}
  orderExpireInterval: {{ .Values.config.entitlementConf.orderExpireInterval }} # 24 hours
  intentExpireInterval: {{ .Values.config.entitlementConf.intentExpireInterval }} # 15 minutes
workspace:
{{- with .Values.config.workspace }}
  {{- toYaml . | nindent 2 }}
{{- end }}
statsConf:
{{- with .Values.config.statsConf }}
  {{- toYaml . | nindent 2 }}
{{- end }}
jaegerConf:
{{- with .Values.config.jaegerConf }}
  {{- toYaml . | nindent 2 }}
{{- end }}
models:
{{- if .Values.config.models -}}
  {{- range .Values.config.models }}
  - id: {{ .id }}
    name: {{ .name }}
  {{- end }}
{{- else }} []
{{- end }}
invitationCode:
  enabled: {{ .Values.config.invitationCode.enabled}}
permissionBasedExport:
  enabled: {{ .Values.config.permissionBasedExport.enabled }}
wechat:
  appID: {{ .Values.config.wechat.appID }}
  appSecret: {{ .Values.config.wechat.appSecret }}
{{- if .Values.innerConfig }}
{{ toYaml .Values.innerConfig }}
{{- end }}
