server:
  http:
    addr: 0.0.0.0:{{ .Values.service.http }}
    timeout: 60s # max timeout, not real timeout
    corsAllowOrigins:
    {{- range .Values.config.server.http.corsAllowOrigins }}
    - {{ . | quote}}
    {{- end }}
    corsAllowHeaders:
    {{- range .Values.config.server.http.corsAllowHeaders }}
    - {{ . | quote }}
    {{- end }}
  grpc:
    addr: 0.0.0.0:{{ .Values.service.grpc }}
    timeout: 300s # max timeout, not real timeout
  shutdownTimeout: {{ .Values.config.server.shutdownTimeout }}
data:
  database:
    maxOpenConns: {{ .Values.config.database.maxOpenConns }}
    maxIdleConns: {{ .Values.config.database.maxIdleConns }}
    connMaxLifetime: {{ .Values.config.database.connMaxLifetime }}
    driver: {{ .Values.config.database.driver }}
    database: {{ .Values.config.database.dbname }}
    dsn: ""
    replicaDSN: ""
  rabbitmq:
    enabled: {{ .Values.config.rabbitmq.enabled }}
    addr: ""
    {{- with .Values.config.rabbitmq.cluster }}
    cluster:
      {{- $cluster := deepCopy . }}
      {{- $_ := set $cluster "username" "" }}
      {{- $_ := set $cluster "password" "" }}
      {{- toYaml $cluster | nindent 6 }}
    {{- end }}
    eventSync: {{ .Values.config.rabbitmq.eventSync }}
  temporal:
    addr: {{ tpl .Values.config.temporal.addr . }}
    namespace: {{ .Values.config.temporal.namespace }}
  {{- with .Values.config.redis }}
  redis:
    {{- $redis := deepCopy . }}
    {{- $_ := set $redis "username" "" }}
    {{- $_ := set $redis "password" "" }}
    {{- $_ := set $redis.sentinel "username" "" }}
    {{- $_ := set $redis.sentinel "password" "" }}
    {{- $_ := set $redis.tlsConfig "key" "" }}
    {{- toYaml $redis | nindent 4 }}
  {{- end }}
  {{- with .Values.config.s3 }}
  s3:
    {{- $s3 := deepCopy . }}
    {{- $_ := set $s3 "accessKeyID" "" }}
    {{- $_ := set $s3 "accessKeySecret" "" }}
    {{- toYaml $s3 | nindent 4 }}
  {{- end }}
service:
  apply:
    addr: "{{ tpl .Values.config.apply.host . }}:{{ .Values.config.apply.port }}"
    timeout: 10s
  collaborationHelper:
    addr: {{ .Values.config.collaborationHelper.addr }}
    timeout: 180s
  {{- if .Values.config.fileExchange.enabled }}
  fileExchange:
    {{- toYaml .Values.config.fileExchange | nindent 4 }}
  {{- end }}
  ssc:
    addr: "{{ tpl .Values.config.ssc.host . }}:{{ .Values.config.ssc.port }}"
    timeout: 10s
unitRoutingConf:
  tiers:
    - tierName: normal
      enable: true
      upgradeCellsThreshold: 0
      downgradeCellsThreshold: 0
      upgradeImportTimeThreshold: 0
      applyServerAddr: "{{ tpl .Values.config.apply.host . }}:{{ .Values.config.apply.port }}"
      applyServerTimeout: 10s
    - tierName: large
      enable: true
      upgradeCellsThreshold:  1000000 # 1M cells
      downgradeCellsThreshold: 900000 # 0.9M cells
      upgradeImportTimeThreshold: 10
      applyServerAddr: "{{ tpl .Values.config.apply.host . }}:{{ .Values.config.apply.port }}"
      applyServerTimeout: 10s
  cacheSeconds: 900
  refreshSeconds: 60
  tierSwitchDelaySeconds: 60
apiLimit:
  {{- with .Values.config.apiLimit }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
auth:
  enabled: {{ .Values.config.auth.enabled }}
  {{- with .Values.config.auth.anonymous }}
  anonymous:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.config.auth.permission }}
  permission:
    {{- toYaml . | nindent 4 }}
  {{- end }}
usip:
  enabled: {{ .Values.config.usip.enabled }}
  apikey: ""
  {{- with .Values.config.usip.uri }}
  uri:
    {{- toYaml . | nindent 4 }}
  {{- end }}
sentryConfig:
  dsn: ""
  debug: false
  enableTracing: true
  TracesSampleRate: 1.0
dataProtectionConf:
  enableProtection: {{ .Values.config.dataProtectionConf.enableProtection }}
  dataKeyRotate: {{ .Values.config.dataProtectionConf.dataKeyRotate }}
  dataKeyCacheExpiration: {{ .Values.config.dataProtectionConf.dataKeyCacheExpiration }}
  {{- if eq .Values.config.dataProtectionConf.kmsServiceName "aws" }}
  awskms:
    accessKeyID: ""
    accessKeySecret: ""
    region: {{ .Values.config.dataProtectionConf.awskms.region }}
    kmsKeyID: ""
  {{- else if eq .Values.config.dataProtectionConf.kmsServiceName "local" }}
  localKMS:
    cmkAlias: {{ .Values.config.dataProtectionConf.localKMS.cmkAlias }}
    cmkBase64: ""
  {{- end }}
workspace:
{{- with .Values.config.workspace }}
  {{- toYaml . | nindent 2 }}
{{- end }}
statsConf:
{{- with .Values.config.statsConf }}
  {{- toYaml . | nindent 2 }}
{{- end }}
jaegerConf:
{{- with .Values.config.jaegerConf }}
  {{- toYaml . | nindent 2 }}
{{- end }}
permissionBasedExport:
  enabled: {{ .Values.config.permissionBasedExport.enabled }}
{{- if .Values.innerConfig }}
{{ toYaml .Values.innerConfig }}
{{- end }}
unitPreLoadConf:
{{- with .Values.config.unitPreLoadConf }}
  {{- toYaml . | nindent 2 }}
{{- end }}
secretManagerConf:
{{- with .Values.config.secretManagerConf }}
  {{- toYaml . | nindent 2 }}
{{- end }}
