server:
  http:
    addr: 0.0.0.0:{{ .Values.service.http }}
    timeout: 10s
  grpc:
    addr: 0.0.0.0:{{ .Values.service.grpc }}
    timeout: 10s
data:
  database:
    driver: postgresql
    database: {{ .Values.config.postgresql.database }}
    dsn: host={{ .Values.config.postgresql.host }} port={{ .Values.config.postgresql.port }} dbname={{ .Values.config.postgresql.database }} user={{ .Values.config.postgresql.username }} password={{ .Values.config.postgresql.password }} sslmode=disable TimeZone=Asia/Shanghai
  rabbitmq:
    addr: amqp://{{ .Values.config.rabbitmq.username }}:{{ .Values.config.rabbitmq.password }}@{{ .Values.config.rabbitmq.host }}:{{ .Values.config.rabbitmq.port }}/
  clickhouse:
    dsn: clickhouse://clickhouse:clickhouse@clickhouse:9000/univer?dial_timeout=10s&read_timeout=20s
  temporal:
    addr: univer-temporal:7233
    namespace: default
    worker_task_queue: migration-task-queue
  redis:
    addr: {{ .Values.config.redis.addr }}
    read_timeout: 0.2s
    write_timeout: 0.2s
  s3:
    accessKeyID: {{ .Values.config.s3.accessKeyID }}
    accessKeySecret: {{ .Values.config.s3.accessKeySecret }}
    region: {{ .Values.config.s3.region }}
    endpoint: {{ .Values.config.s3.endpoint }}
    usePathStyle: {{ .Values.config.s3.usePathStyle }}
    presignExpires: {{ .Values.config.s3.presignExpires }}
service:
  transform:
    addr: "{{ .Values.config.transform.host }}:{{ .Values.config.transform.port }}"
    timeout: 10s
  apply:
    addr: "{{ .Values.config.apply.host }}:{{ .Values.config.apply.port }}"
    timeout: 10s
  node_snapshot:
    addr: "{{ .Values.config.node_snapshot.host }}:{{ .Values.config.node_snapshot.port }}"
    timeout: 10s
admin: 
{{- if .Values.config.admin -}}
  {{- range .Values.config.admin }}
  - user: {{ .user }}
    password: {{ .password }}
  {{- end }}
{{- else }} []
{{- end }}
extra:
  celldataMaxSize: 10485760 # 单位字节，10M