{
 "title": "collaboration-server",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "system metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage(relative to limit)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"univer\", pod=~\".*collaboration-server.*\"}[2m])*100)by(pod) / sum(container_spec_cpu_quota{namespace=\"univer\", pod=~\".*collaboration-server.*\"} / container_spec_cpu_period{namespace=\"univer\", pod=~\".*collaboration-server.*\"})by(pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "memory usage(relative to limit)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"univer\", pod=~\".*collaboration-server.*\"}) by (pod)\r\n/ sum(container_spec_memory_limit_bytes{namespace=\"univer\", pod=~\".*collaboration-server.*\"}) by (pod) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ingress technical metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "ingress SLI(in the selected range) by API",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(univer_requests_counter{code!=\"2\"}[$__range]))by(method) / sum(rate(univer_requests_counter{}[$__range]))by(method) *100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "biz error code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (code, method) (increase(univer_requests_counter{code!=\"OK\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ingress total QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(univer_requests_counter{}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ingress SLI",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(univer_requests_counter{code=\"OK\"}[2m])) / sum(rate(univer_requests_counter{}[2m])) *100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ingress PCT99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(univer_requests_duration_sec_bucket{job=\"collaboration\"}[2m])) by (method, le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ingress API QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (method) (rate(univer_requests_counter[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ingress SLI group by API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(univer_requests_counter{code=\"OK\"}[2m]))by(method) / sum(rate(univer_requests_counter{}[2m]))by(method) *100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "biz metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "unit in memory num",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(univer_unit_gauge) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "unit load count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
     "targets": [
      {
       "expr": "sum(univer_unit_load) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "unit unload",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(univer_unit_unload) by(instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "unit load to unload time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "targets": [
      {
       "expr": "univer_unit_load_to_unload_duration_sec_bucket",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "changeset_p50",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile(0.5, univer_changeset_summary{}) by (type, operation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "changeset_p99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile(0.99, univer_changeset_summary{}) by (type, operation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "unload unit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (reason) (increase(univer_unit_unload[2m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}