{
 "title": "Exchange Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Namespace" },
   { "name": "WorkflowType" }
  ]
 },
 "panels": [
  {
   "title": "import parse from excel latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "univer_exchange_worker_import_parse_latency{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "exchange save to excel latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "univer_exchange_worker_export_save_latency{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "import marshal latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "univer_exchange_worker_import_marshal_to_json_latency{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "univer_exchange_worker_import_marshal_to_unit_latency{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "export unmarshal latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "univer_exchange_worker_export_unmarshal_from_unit_latency{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "univer_exchange_worker_export_unmarshal_from_json_latency{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "import/export number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "univer_exchange_worker_activity_succeeded_total{operation=\"export_Convert\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(univer_exchange_worker_activity_succeeded_total{operation=\"import_Convert\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}