{
 "title": "Universer",
 "tags": [
  "QPS",
  "Latency",
  "SLA"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "system metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "universer CPU usage percent(relative to limit)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"univer\", pod=~\".*universer.*\"}[2m])*100)by(pod) / sum(container_spec_cpu_quota{namespace=\"univer\", pod=~\".*universer.*\"} / container_spec_cpu_period{namespace=\"univer\", pod=~\".*universer.*\"})by(pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "universer memory usage percent(relative to limit)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"univer\", pod=~\".*universer.*\"}) by (pod)\r\n/ sum(container_spec_memory_limit_bytes{namespace=\"univer\", pod=~\".*universer.*\"}) by (pod) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "memory used total",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (instance)(go_memstats_sys_bytes{instance=~\".*:8000\", job=\"universer\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Stack Memory Use",
     "type": "graph",
     "description": "Average stack memory usage across all instances of a job.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg by (job) (go_memstats_stack_sys_bytes{job=\"universer\", instance=~\".*:8000\"})"
      }
     ]
    },
    {
     "title": "Total Reserved Memory",
     "type": "graph",
     "description": "Average total bytes of memory reserved across all process instances of a job.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg by(job)(go_memstats_sys_bytes{job=\"universer\", instance=~\".*:8000\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Next GC, Bytes",
     "type": "graph",
     "description": "The number used bytes at which the runtime plans to perform the next GC, averaged across all instances of a job.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg by (job)(go_memstats_next_gc_bytes{job=\"universer\", instance=~\".*:8000\"})"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "description": "Average number of goroutines across instances of a job.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(go_goroutines{job=\"universer\", instance=~\".*:8000\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "RDS biz side",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS group by cmd",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(univer_rds_count[2m]))by(cmd)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "success P99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile(0.99, univer_rds_latency{success=\"true\"}) by (cmd)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Fail P99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile(0.99, univer_rds_latency{success=\"false\"}) by (cmd)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLI group by cmd",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(univer_rds_count{success=\"true\"}[2m]))by(cmd) / sum(rate(univer_rds_count[2m]))by(cmd) *100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis biz side",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS group by cmd",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(univer_redis_count[2m]))by(cmd)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLI group by cmd",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(univer_redis_count{success=\"true\"}[2m]))by(cmd) / sum(rate(univer_redis_count[2m]))by(cmd) *100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "success P99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile(0.99, univer_redis_latency{success=\"true\"}) by (cmd)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "MQ biz side",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "publish QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(univer_mq_pubcount{success=\"true\"}[2m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum(rate(univer_mq_pubcount{success=\"false\"}[2m]))",
       "legendFormat": "fail"
      }
     ]
    },
    {
     "title": "publish SLI",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(univer_mq_pubcount{success=\"true\"}[2m])) / sum(rate(univer_mq_pubcount[2m])) *100",
       "legendFormat": "SLI"
      }
     ]
    },
    {
     "title": "publish success P9x",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile(0.99, univer_mq_publatency{success=\"true\"})",
       "legendFormat": "P99"
      },
      {
       "expr": "quantile(0.90, univer_mq_publatency{success=\"true\"})",
       "legendFormat": "P90"
      }
     ]
    }
   ]
  },
  {
   "title": "USIP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS group by API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(rate(univer_usip_count{}[2m]))by(operation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLI group by API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(univer_usip_count{status_code=\"200\"}[2m]))by(operation) / sum(rate(univer_usip_count{}[2m]))by(operation) *100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status code[2m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (status_code, operation) (increase(univer_usip_count{status_code!=\"200\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "success P99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile(0.99, univer_usip_latency{success=\"true\"}) by (operation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Fail P99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile(0.99, univer_usip_latency{success=\"false\"}) by (operation)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ingress technical metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "ingress SLI",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(univer_requests_QPS{affect_sli=\"false\", direction=\"ingress\"}[2m])) / sum(rate(univer_requests_QPS{direction=\"ingress\"}[2m])) *100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ingress SLI(in the selected range) by API",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(univer_requests_QPS{direction=\"ingress\", affect_sli=\"false\"}[$__range]))by(operation) / sum(rate(univer_requests_QPS{direction=\"ingress\"}[$__range]))by(operation) *100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ingress total QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(rate(univer_requests_QPS{direction=\"ingress\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ingress QPS group by API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "targets": [
      {
       "expr": "sum(rate(univer_requests_QPS{direction=\"ingress\", operation!=\"/grpc.health.v1.Health/Check\"}[2m]))by(operation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ingress SLI group by API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(univer_requests_QPS{direction=\"ingress\", affect_sli=\"false\"}[2m]))by(operation) / sum(rate(univer_requests_QPS{direction=\"ingress\"}[2m]))by(operation) *100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ingress success P99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile(0.99, univer_requests_Latency{direction=\"ingress\", success=\"true\", operation!=\"/universer-api/stream/file/upload\"}) by (operation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ingress Fail P99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile(0.99, univer_requests_Latency{direction=\"ingress\", success=\"false\"}) by (operation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "biz_code[2m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (biz_code, operation) (increase(univer_requests_QPS{direction=\"ingress\", biz_code!=\"1\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "http status code[2m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (http_code, operation) (increase(univer_requests_QPS{direction=\"ingress\", http_code!=\"200\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "egress technical metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "egress total QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(rate(univer_requests_QPS{direction=\"egress\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "egress SLI",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(univer_requests_QPS{affect_sli=\"false\", direction=\"egress\"}[2m])) / sum(rate(univer_requests_QPS{direction=\"egress\"}[2m])) *100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "egress success P99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile(0.99, univer_requests_Latency{direction=\"egress\", success=\"true\"}) by (operation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "egress QPS group by API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum(rate(univer_requests_QPS{direction=\"egress\"}[2m]))by(operation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "egress SLI group by API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(univer_requests_QPS{direction=\"egress\", affect_sli=\"false\"}[2m]))by(operation) / sum(rate(univer_requests_QPS{direction=\"egress\"}[2m]))by(operation) *100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "egress Fail P99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile(0.99, univer_requests_Latency{direction=\"egress\", success=\"false\"}) by (operation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "biz_code[2m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (biz_code, operation) (increase(univer_requests_QPS{direction=\"egress\", biz_code!=\"1\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "biz metrics--collaborative edit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "changeset QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(univer_requests_QPS{direction=\"ingress\", operation=\"/universer.v1.CombService/NewChanges\"}[2m]))",
       "legendFormat": "new changeset"
      },
      {
       "expr": "sum(rate(univer_requests_QPS{direction=\"egress\", operation=\"/univerpro.v1.ApplyService/Apply\"}[2m]))",
       "legendFormat": "apply changeset"
      }
     ]
    },
    {
     "title": "changeset apply SLI",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(univer_requests_QPS{affect_sli=\"false\", direction=\"egress\", operation=\"/univerpro.v1.ApplyService/Apply\"}[2m])) / sum(rate(univer_requests_QPS{direction=\"egress\", operation=\"/univerpro.v1.ApplyService/Apply\"}[2m])) *100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "changeset operate latency p99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile(0.99, univer_collaboration_cs_operate_latency{}) by (step)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "wss connections total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum(univer_wss_connect_total_gauge)",
       "legendFormat": "connections"
      }
     ]
    },
    {
     "title": "wss connect/disconnect QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
     "targets": [
      {
       "expr": "sum (rate(univer_wss_operation_count{operation=\"open\"}[2m]))",
       "legendFormat": "connect"
      },
      {
       "expr": "sum (rate(univer_wss_operation_count{operation=\"close\"}[2m]))",
       "legendFormat": "disconnect"
      }
     ]
    },
    {
     "title": "room join/leave QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
     "targets": [
      {
       "expr": "sum (rate(univer_rooms_operation_count{}[2m])) by (operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "event total QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (rate(univer_wss_msg_events_count[2m])) by (eventId)",
       "legendFormat": "{{eventId}}"
      }
     ]
    },
    {
     "title": "event filtered QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (rate(univer_wss_msg_events_count{filtered=\"true\"}[2m])) by (eventId)",
       "legendFormat": "{{eventId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "biz metrics--exchange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "import",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum (rate(univer_requests_QPS{operation=\"/universer.v1.ExchangeService/Import\",http_code=\"200\",biz_code=\"1\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "export",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum (rate(univer_requests_QPS{operation=\"/universer.v1.ExchangeService/Export\",http_code=\"200\",biz_code=\"1\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}