limit.maxIDLength:
  - value: 255
    constraints: {}
system.forceSearchAttributesCacheRefreshOnRead:
  - value: false # Dev setup only. Please don't turn this on in production. on is true
    constraints: {}
