apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cibot.fullname" . }}-config
  labels:
    {{- include "cibot.labels" . | nindent 4 }}
data:
  .env: |
    SERVER_PORT={{ .Values.service.port }}
    SERVER_HOST=0.0.0.0

    APP_ID={{ .Values.app.appId }}
    PRIVATE_KEY_PATH=/app/github.pem
    WEBHOOK_SECRET=univer

    APP_INSTALLATION_ID={{ .Values.app.installationId }}
    WEBHOOK_PROXY_URL={{ .Values.app.webhookProxyUrl }}

    RULES_CONFIG_PATH=/app/rule-config

    {{- if .Values.app.extraEnv -}}
    {{ .Values.app.extraEnv }}
    {{- end }}