apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cibot.fullname" . }}-secret
  labels:
    {{- include "cibot.labels" . | nindent 4 }}
data:
  github.pem: {{ .Values.app.githubPem | b64enc | quote }}