server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://univer-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker_scrape
    pipeline_stages:
      - docker: {}
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: [com.univer.app]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        regex: '(.*)'
        target_label: 'stream'
      - source_labels: ['__meta_docker_network_ip']
        regex: '(.*)'
        target_label: 'ip'
      - source_labels: ['__meta_docker_container_label_com_univer_app']
        regex: '(.*)'
        target_label: 'app'