apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cibot-rule.fullname" . }}
  labels:
    {{- include "cibot-rule.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "rule/{{ .Values.path }}/**").AsConfig | indent 2 }}