{{- if .Values.istio.enabled -}}
{{- if and (not .Values.ingress.enabled) .Values.istio.gateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "collaboration-demo.fullname" . }}-gws
  labels:
    {{- include "collaboration-demo.labels" . | nindent 4 }}
spec:
  hosts:
  {{- range .Values.istio.gateway.hosts }}
  - {{ . | quote }}
  {{- end }}
  gateways:
  - univer
  http:
  - match:
      - uri:
          prefix: "/pro-demo/"
    delegate:
      name: {{ include "collaboration-demo.fullname" . }}
    headers:
      request:
        remove: [ x-feature-id ]
{{- end }}
---
{{- if and (not .Values.ingress.enabled) .Values.istio.featureGateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "collaboration-demo.fullname" . }}-feat-gws
  labels:
    {{- include "collaboration-demo.labels" . | nindent 4 }}
spec:
  hosts:
  {{- range .Values.istio.featureGateway.hosts }}
  - {{ . | quote }}
  {{- end }}
  gateways:
  - univer-feature
  http:
  - match:
      - uri:
          prefix: "/pro-demo/"
    delegate:
      name: {{ include "collaboration-demo.fullname" . }}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "collaboration-demo.fullname" . }}
  labels:
    {{- include "collaboration-demo.labels" . | nindent 4 }}
spec:
  {{- if and (not .Values.istio.gateway.enabled) (not .Values.istio.featureGateway.enabled) }}
  hosts:
    - {{ include "collaboration-demo.fullname" . | quote }}
  {{- end }}
  http:
    - route:
        - destination:
            host: {{ include "collaboration-demo.fullname" . }}
            port: 
              number: {{ .Values.service.port }}
            subset: default
{{- end -}}